gcp_project_id = "your_project_id"
gcp_region = "us-central1"
azure_subscription_id = "your_subscription_id"
openstack_auth_url = "http://your-openstack-auth-url"
openstack_username = "your-username"
openstack_password = "your-password"
openstack_tenant_name = "your-tenant-name"
